import { StyleSheet } from "react-native";
import type { AppColors } from "../lib/theme/types";

export function createRoutePlanStyles(c: AppColors) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.background },
    scroll: { paddingBottom: 120 },
    lead: {
      paddingHorizontal: 16,
      paddingTop: 12,
      fontSize: 13,
      color: c.textSecondary,
      lineHeight: 18,
    },
    leadStrong: { fontWeight: "700", color: c.text },
    trackingCard: {
      marginHorizontal: 16,
      marginTop: 14,
      padding: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    trackingCardActive: {
      borderColor: c.primary,
      backgroundColor: c.surface,
    },
    trackingTitle: { fontSize: 15, fontWeight: "700", color: c.text },
    trackingDescription: {
      marginTop: 4,
      fontSize: 12,
      lineHeight: 17,
      color: c.textSecondary,
    },
    trackingButton: {
      backgroundColor: c.primary,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    trackingButtonStop: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.primary,
    },
    trackingButtonText: {
      color: c.primaryForeground,
      fontSize: 13,
      fontWeight: "700",
    },
    trackingButtonStopText: { color: c.primary },
    filterRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingHorizontal: 16,
      marginTop: 12,
      alignItems: "center",
    },
    visitBanner: {
      marginHorizontal: 16,
      marginTop: 12,
      padding: 14,
      borderRadius: 14,
      backgroundColor: c.warningSurface,
      borderWidth: 1,
      borderColor: c.warning,
      gap: 12,
    },
    visitRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    visitTitle: { fontSize: 16, fontWeight: "700", color: c.text },
    visitSub: {
      marginTop: 4,
      fontSize: 14,
      fontWeight: "600",
      color: c.textSecondary,
    },
    visitActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    checkOutBtn: {
      backgroundColor: c.warning,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 10,
    },
    checkOutTxt: {
      color: c.primaryForeground,
      fontWeight: "700",
      fontSize: 15,
    },
    saleBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.primary,
    },
    saleBtnTxt: { color: c.primary, fontWeight: "700", fontSize: 14 },
    toolbar: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      paddingHorizontal: 16,
      marginTop: 14,
    },
    toolBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    toolBtnTxt: { fontWeight: "600", color: c.link, fontSize: 14 },
    toolBtnPrimary: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: c.primary,
    },
    toolBtnPrimaryTxt: {
      fontWeight: "700",
      color: c.primaryForeground,
      fontSize: 14,
    },
    btnDis: { opacity: 0.5 },
    err: { marginHorizontal: 16, marginTop: 8, color: c.danger, fontSize: 13 },
    warn: {
      marginHorizontal: 16,
      marginTop: 8,
      color: c.warning,
      fontSize: 13,
    },
    map: {
      marginHorizontal: 16,
      marginTop: 12,
      height: 280,
      borderRadius: 14,
      overflow: "hidden",
    },
    mapHint: {
      textAlign: "center",
      fontSize: 12,
      color: c.textMuted,
      paddingHorizontal: 24,
      marginTop: 6,
    },
    mapHintBtn: { paddingVertical: 4 },
    routeBox: {
      marginHorizontal: 16,
      marginTop: 14,
      padding: 12,
      borderRadius: 12,
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
      gap: 6,
    },
    routeTitle: { fontWeight: "700", color: c.text, marginBottom: 4 },
    routeDisclaimer: { fontSize: 12, color: c.textSecondary, marginBottom: 8 },
    routeLegMeta: {
      marginHorizontal: 16,
      marginTop: 10,
      fontSize: 11,
      fontWeight: "600",
      color: c.textMuted,
    },
    clearRoute: {
      marginTop: 8,
      fontSize: 13,
      fontWeight: "600",
      color: c.primary,
    },
    section: {
      marginHorizontal: 16,
      marginTop: 18,
      fontSize: 15,
      fontWeight: "700",
      color: c.text,
    },
    empty: {
      marginHorizontal: 16,
      marginTop: 8,
      color: c.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    visitHist: {
      marginHorizontal: 16,
      marginTop: 8,
      paddingVertical: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    visitHistName: { fontWeight: "600", color: c.text },
    visitHistMeta: { marginTop: 2, fontSize: 12, color: c.textMuted },
    linkQuickSale: { marginHorizontal: 16, marginTop: 24, marginBottom: 8 },
    linkQuickSaleTxt: { fontSize: 15, fontWeight: "700", color: c.primary },
  });
}
